### ISSUE TITLE
where oh where is cstub

### ISSUE THREAD

**Issue by timmywu** [mcowger/vpnsplit2#1]
Executing /opt/cisco/hostscan/bin/cstub -url "https://hop04-l1i07-vn01.emc.com/CACHE/sdesktop/install/result.htm" -ticket "2CEEA8A2447EE46D66FCD484" -stub "0" -certhash "66E530E480CD857C2A431220C77337BC:"
/Users/######/.vpn/cstub.sh: line 37: /opt/cisco/hostscan/bin/cstub: No such file or directory

$ ls -lah /opt/cisco/
total 0
drwxr-xr-x   4 root  wheel   136B Jul 28 10:00 .
drwxr-xr-x@  4 root  wheel   136B Jun 16 20:22 ..
drwxr-xr-x  18 root  wheel   612B Jul 26 19:48 anyconnect
drwxr-xr-x   4 root  wheel   136B Jun 16 20:21 vpn

Anyconnect version 3.1.04074 automatically installed with Mavericks IT image

**Comment by osaddict** [comment]
That fix it for me too. Thanks again Matt!

**Comment by akutz** [comment]
You can also hit up one of the AnyConnect URLs and give it the following URL suffix to grab it: https://VPN_URL/CACHE/sdesktop/hostscan/darwin_i386/cstub
